version: 0
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        env: true
        events:
          - push
        branches:
          - auto
          - master
          - try
    payload:
      maxRunTime: 3600
      image: ubuntu@sha256:edf05697d8ea17028a69726b4b450ad48da8b29884cd640fec950c904bfb50ce
      command:
        - /usr/bin/env
        - DEBIAN_FRONTEND=noninteractive
        - bash
        - '--login'
        - '-c'
        - >-
          :
          && apt-get update
          && apt-get install -y --no-install-recommends git
          && git clone {{event.head.repo.url}} saltfs
          && cd saltfs
          && git config advice.detachedHead false
          && git checkout {{event.head.sha}}
          && ./etc/build_image.sh
    metadata:
      name: Servo Trusty OCI image builder
      description: Build Trusty OCI images using Salt for building/testing Servo
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
